name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file api/Dockerfile --tag dummy_api:latest

      - name: Build docker image & push to dockerhub
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: kyalepeter/dummy_api
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD}}
